### Cargamos Ontologia

In [1]:
import sys
# insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, '../Scripts')
import pandas as pd 
from ontologia import *
import ast
import difflib

#Lectura de lemas 
import json
with open('./Vocabulario/diccionario-lemas.json', 'r') as f:
    diccionario_lemas = json.loads(f.read())

lemas = list(diccionario_lemas.keys())

### Cargamos Modelo W2V

In [167]:
from gensim.test.utils import datapath
from gensim import utils
from gensim.models import Word2Vec
import multiprocessing
from time import time

modelo = Word2Vec.load("./Modelos/modelo10FINAL.model")

In [19]:
len(list(modelo.wv.vectors))

11445

In [40]:
len(modelo.wv.vocab)

11445

In [168]:
vectores = list(modelo.wv.vectors)
len(vectores[0])

300

In [ ]:
modelo.wv.cosine_similarities()

In [169]:
keyedvectors = modelo.wv
keyedvectors.save('vectors.kv')
del(modelo)

In [1]:
from gensim.models import KeyedVectors
keyedvectors = KeyedVectors.load('vectors.kv')

In [5]:
keyedvectors.similarity

3433500

In [8]:
words = ['gestor', 'conocimiento']
#Modelo W2v
similar_words = keyedvectors.most_similar(words, topn=10)
similar_words

[('debilmente', 0.77090984582901),
 ('umayux', 0.7446715831756592),
 ('sgbd', 0.7438246011734009),
 ('sparql', 0.7421228885650635),
 ('rdf', 0.7153308391571045),
 ('postgresql', 0.7092360854148865),
 ('ontologias', 0.7078660726547241),
 ('fundamentandose', 0.699651837348938),
 ('solicitada', 0.6902329921722412),
 ('maskana', 0.6835665702819824)]

# MOST SIMILAR 

In [185]:
keyedvectors.word_vec('conocimiento', use_norm=True)

array([-5.83143793e-02,  2.25428659e-02, -1.40660226e-01,  4.73534279e-02,
        4.85370159e-02, -2.98704095e-02,  9.87917185e-02, -6.42506406e-02,
       -6.29628599e-02,  2.13934574e-02,  1.74135622e-02,  3.02295038e-03,
       -9.79842395e-02, -1.74497142e-02,  8.29045195e-04,  1.06558308e-01,
       -9.20203626e-02,  2.35471167e-02, -8.16599950e-02,  8.49523470e-02,
        4.94701080e-02, -1.12909205e-01,  4.89118844e-02,  1.06700398e-01,
       -2.74970178e-02,  6.21169386e-03,  2.86916588e-02, -5.79602569e-02,
        4.31696810e-02,  1.11009374e-01,  5.13817519e-02, -8.28848034e-03,
       -3.27971093e-02,  3.80460825e-03, -5.09236269e-02,  8.00407231e-02,
        7.45652989e-03,  5.74851467e-04, -1.82522871e-02, -3.68378572e-02,
       -1.21693751e-02,  4.33343798e-02,  8.92285928e-02, -4.33225073e-02,
        2.76588788e-03, -7.20632672e-02, -8.34282767e-03,  8.30176771e-02,
       -1.13498732e-01,  7.71138933e-04,  3.66494581e-02, -2.02630367e-02,
        2.47475728e-02, -

In [242]:
from numpy import (
    dot, float32 as REAL
)
import numpy as np

from gensim import matutils

mean = [keyedvectors.get_vector('conocimiento')*1.0,keyedvectors.get_vector('gestor')*1.0]
array = np.array(mean)
#mean = matutils.unitvec(array.mean(axis=0)).astype(REAL)
array.mean(axis=0)

array([-1.23168334e-01,  1.57891661e-01, -6.25096321e-01,  3.70365083e-01,
        1.39905602e-01, -9.60560292e-02,  4.60902035e-01, -2.39172742e-01,
       -2.81502545e-01,  1.50287807e-01,  4.66603264e-02, -1.49352513e-02,
       -2.12155104e-01, -1.27391472e-01, -2.89045960e-01,  1.60912141e-01,
       -4.02316093e-01,  1.88893974e-01, -3.37589920e-01,  3.65222931e-01,
        1.61029562e-01, -3.79429370e-01,  3.99879813e-01,  5.25689602e-01,
       -1.93456918e-01,  4.70395461e-02,  2.32833818e-01,  5.63850999e-03,
        2.12130308e-01,  6.24908805e-01,  1.86493725e-01, -8.82985145e-02,
        1.73825473e-01,  1.36649668e-01, -1.22122943e-01,  2.15896994e-01,
        8.02406818e-02, -3.88773438e-03, -1.18246935e-02, -7.17988908e-02,
        5.18715829e-02,  3.54395270e-01,  4.26124036e-01, -2.57471263e-01,
       -6.19445816e-02, -4.32184219e-01, -8.69711563e-02,  3.19565952e-01,
       -5.13556540e-01,  4.33931798e-02,  5.10791615e-02,  4.06885892e-02,
        1.85201645e-01, -

In [214]:
from numpy import linalg as LA
norms=[]
for vector in keyedvectors.vectors:
    norms.append(LA.norm(vector))

In [237]:
dist = np.dot(keyedvectors.vectors[0:None], mean) / norms[0:None]
best = matutils.argsort(dist, topn=10 + 2, reverse=True) 
best

array([   19,  4918,  4933,  6680,  6681,  6645,  6646,  2202, 11380,
       11195, 11197, 11379])

In [ ]:
result = [
            (self.index_to_key[sim + clip_start], float(dists[sim]))
            for sim in best if (sim + clip_start) not in all_keys
        ]
return result[:topn]

In [239]:
keyedvectors.index2word[4933]

'debilmente'

In [217]:
words = list(keyedvectors.vocab.keys())
words[4917]

'adaptar'

In [137]:
keyedvectors.most_similar(['conocimiento', 'gestor'], topn=10)

[('debilmente', 0.77090984582901),
 ('umayux', 0.7446715831756592),
 ('sgbd', 0.7438246011734009),
 ('sparql', 0.7421228885650635),
 ('rdf', 0.7153308391571045),
 ('postgresql', 0.7092360854148865),
 ('ontologias', 0.7078660726547241),
 ('fundamentandose', 0.699651837348938),
 ('solicitada', 0.6902329921722412),
 ('maskana', 0.6835665702819824)]

# END

### Lectura de palabras

In [54]:
words = ['gestor', 'conocimiento']
#Modelo W2v
similar_words = modelo.wv.most_similar(words, topn=20)

words.extend([word[0] for word in similar_words])

#Palabras en plural o muy similares
more_words=[]
for word in words:
    additional = difflib.get_close_matches(word, diccionario_lemas.keys(), n=5, cutoff=0.90)
    more_words.extend(additional[1:])
    
#Añadir palabras finales
words.extend(more_words)
words

['gestor',
 'conocimiento',
 'debilmente',
 'umayux',
 'sgbd',
 'sparql',
 'rdf',
 'postgresql',
 'ontologias',
 'fundamentandose',
 'solicitada',
 'maskana',
 'motor',
 'transformarla',
 'facilite',
 'adquieran',
 'buscador',
 'digitalizados',
 'flock',
 'robusto',
 'publicarlo',
 'divulgarlo',
 'reconocimiento',
 'solicitado',
 'transformarlo',
 'transformar',
 'buscado',
 'flocks']

# Recuperacion con OR2


In [55]:
words_instances=[]

for word in words:
    instance = ontologia.search(descripcion_palabra=word)
    words_instances.extend(instance)

#print(words_instances)
docs = []
id_docs = []
for word in words_instances:
    for doc in word.palabra_describe_pi:
        id_doc = doc.get_id_proyecto_investigacion()[0]
        id_docs.append(id_doc)
        docs.append(doc)

# Ranking by Frequency

In [34]:
Counter(id_docs).most_common()

[(422, 7),
 (94, 5),
 (311, 5),
 (417, 5),
 (63, 4),
 (445, 4),
 (22, 3),
 (223, 2),
 (435, 2),
 (438, 2),
 (389, 2),
 (303, 2),
 (404, 2),
 (24, 2),
 (407, 2),
 (54, 2),
 (189, 2),
 (340, 2),
 (287, 2),
 (120, 1),
 (419, 1),
 (442, 1),
 (361, 1),
 (363, 1),
 (25, 1),
 (26, 1),
 (28, 1),
 (34, 1),
 (38, 1),
 (51, 1),
 (72, 1),
 (76, 1),
 (85, 1),
 (129, 1),
 (134, 1),
 (141, 1),
 (160, 1),
 (171, 1),
 (177, 1),
 (196, 1),
 (200, 1),
 (249, 1),
 (253, 1),
 (278, 1),
 (279, 1),
 (308, 1),
 (338, 1),
 (350, 1),
 (384, 1),
 (385, 1),
 (397, 1),
 (431, 1),
 (33, 1),
 (154, 1),
 (247, 1),
 (248, 1),
 (250, 1),
 (293, 1),
 (138, 1),
 (258, 1),
 (309, 1),
 (405, 1),
 (17, 1),
 (19, 1),
 (77, 1),
 (111, 1),
 (291, 1),
 (369, 1),
 (370, 1),
 (371, 1),
 (381, 1),
 (440, 1),
 (2, 1),
 (64, 1),
 (261, 1),
 (21, 1),
 (65, 1),
 (105, 1),
 (310, 1)]

In [56]:
from collections import Counter 
from itertools import repeat, chain 
    
# printing initial ini_list 
print ("initial list", str(id_docs), "Cantidad:" ,len(id_docs)) 
  
# sorting on bais of frequency of elements 
result = list(chain(i for i, c in Counter(id_docs).most_common())) 
  
# printing final result 
print("final list", str(result), "Cantidad:",len(result)) 


initial list [422, 443, 3, 4, 6, 7, 8, 9, 10, 13, 14, 21, 24, 25, 28, 30, 34, 39, 48, 49, 53, 55, 58, 62, 63, 64, 65, 68, 73, 75, 77, 80, 83, 91, 94, 98, 103, 106, 107, 111, 117, 119, 122, 126, 127, 131, 143, 154, 157, 159, 160, 163, 168, 170, 177, 180, 188, 190, 191, 193, 196, 198, 201, 202, 204, 205, 212, 214, 219, 220, 223, 224, 229, 230, 231, 232, 238, 247, 248, 251, 261, 263, 266, 271, 272, 276, 280, 282, 284, 286, 288, 291, 292, 293, 304, 305, 308, 310, 311, 312, 320, 321, 329, 331, 332, 334, 336, 337, 338, 343, 345, 346, 349, 350, 352, 360, 368, 371, 375, 376, 377, 380, 382, 394, 405, 407, 409, 416, 417, 422, 430, 431, 433, 441, 443, 444, 445, 448, 443, 443, 443, 422, 422, 443, 422, 435, 438, 443, 422, 422, 443, 422, 337, 443, 1, 9, 34, 38, 64, 104, 173, 190, 197, 235, 247, 248, 255, 281, 292, 293, 304, 311, 320, 324, 395, 399, 400, 422, 431, 438, 62, 443, 444, 438, 422, 403, 63, 443, 443, 1, 12, 18, 38, 47, 56, 71, 193, 203, 204, 218, 226, 230, 231, 233, 243, 245, 281, 312, 320

### Ranking con Instancias de Documentos

In [57]:
# printing initial ini_list 
print ("initial list", "Cantidad:" ,len(docs)) 
  
# sorting on bais of frequency of elements 
result = list(chain(i for i, c in Counter(docs).most_common())) 
  
# printing final result
print("final list", "Cantidad:" ,len(result)) 

initial list Cantidad: 226
final list Cantidad: 171


In [58]:
for index, doc in enumerate(result[:20]):
    title = doc.get_titulo_proyecto_investigacion()
    print(f'({index+1}) {title}')

(1) ['UMAYUX: UN MODELO DE SOFTWARE DE GESTION DE CONOCIMIENTO SOPORTADO EN UNA ONTOLOGIA DINAMICA DEBILMENTE ACOPLADO CON UN GESTOR DE BASE DE DATOS PARA LA UNIVERSIDAD DE NARIÑO']
(2) ['MOTOR DE BÚSQUEDA INTELIGENTE DE INFORMES DE INVESTIGACIÓN BASADO EN RECURSOS SEMÁNTICOS PARA EL SISTEMA DE INVESTIGACIONES DE LA UNIVERSIDAD DE NARIÑO']
(3) ['APROXIMACIÓN AL PENSAMIENTO JURÍDICO NARIÑENSE DESDE LAS FIGURAS DE JOSÉ RAFAEL SAÑUDO Y ERNESTO VELA ANGULO.']
(4) ['SITAPP: UNA APLICACIÓN INTELIGENTE PARA DISPOSITIVOS MÓVILES DEL SISTEMA DE RUTAS DE TRANSPORTE URBANO DEL MUNICIPIO DE PASTO']
(5) ['Análisis de factores de aprendizaje en seguridad alimentaria con comunidades rurales en el municipio de Pasto, departamento de Nariño.']
(6) ['CARACTERIZACIÓN AEROBIA Y ANAEROBIA DEL ÁREA DE INFLUENCIA DE LA PRODUCCIÓN DE TRUCHA ARCOÍRIS (Oncorhynchus mykiss) DE LA ESTACIÓN PISCÍCOLA INTIYACO EN EL LAGO GUAMUEZ DEPARTAMENTO DE NARIÑO']
(7) ['Desarrollo de una estrategia pedagógica que facilite la 