In [3]:
from gensim.test.utils import datapath
from gensim import utils
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.models import Word2Vec
from time import time

from numpy import (
    dot, float32 as REAL
)
import numpy as np
from gensim import matutils

Cargar Modelos originales

In [2]:
modeloD2V = Doc2Vec.load("./Modelos/modelo2_FINALD2V.model")
modeloW2V = Word2Vec.load("./Modelos/modelo10FINAL.model")

Obtener Vectores e inferencia

In [ ]:
#GUARDAR MODELO SIN INFERENCIA
modeloD2V.delete_temporary_training_data(keep_doctags_vectors=False, keep_inference=False)
modeloD2V.save('modelofree.model')
modeloD2V.trainables.save('neural.mm')


# Inferir Vectores

In [ ]:
#Vectores y matriz de inferencia
red = modeloD2V.trainables.save('neural.mm')
vectorlockf = red.vectors_lockf
syn1neg = red.syn1neg
del(red)

In [ ]:
modelo.trainables.vectors_lockf = vectorlockf
modelo.trainables.syn1neg = syn1neg
del(vectorlockf)
del(syn1neg)

In [ ]:
modelo.infer_vector(['hola'])

# Función similiar w2v

In [ ]:
keyedvectors = modeloW2V.wv
#keyedvectors.save('vectors.kv')
del(modeloW2V)

##### modelo original

In [ ]:
words = ['gestor', 'conocimiento']
#Modelo W2v
similar_words = keyedvectors.most_similar(words, topn=10)
similar_words

##### Pesos a las palabras y encontrar la media

In [29]:
from numpy import (
    dot, float32 as REAL
)
import numpy as np

from gensim import matutils

mean = [keyedvectors.get_vector('conocimiento')*1.0,keyedvectors.get_vector('gestor')*1.0]
array = np.array(mean)
#mean = matutils.unitvec(array.mean(axis=0)).astype(REAL)
array.mean(axis=0)

NameError: name 'keyedvectors' is not defined

##### Vectores normalizados

In [ ]:
from numpy import linalg as LA
norms=[]
for vector in keyedvectors.vectors:
    norms.append(LA.norm(vector))

##### Producto punto y normalizar 
Ordenar de mayor a menor y su cantidad

In [ ]:
dist = np.dot(keyedvectors.vectors[0:None], mean) / norms[0:None]
best = matutils.argsort(dist, topn=10 + 2, reverse=True) 
best

##### Encontrar la palabra

In [ ]:
keyedvectors.index2word[4933]

### Función Similar W2V old versión

In [3]:
modeloW2V.wv.init_sims()

In [4]:
#indice Enumerate
#print(modeloW2V.wv.vectors) Vector
print(modeloW2V.wv.index2word[1]) # palabra
#from numpy import linalg as 
#LA.norm(vector) Norm Vector

nariño


In [45]:
array = [modeloW2V.wv.vectors_norm[1]*1.0, modeloW2V.wv.vectors_norm[4]*1.0]
array1 = array[0]
array_mean=np.array(array).mean(axis=0)

In [120]:
final_mean = []
for vector in array:
    final_mean.append(sum(vector.tolist()) / len(vector))
final_mean

[-0.004976595592840264, -0.00048409564726171084]

In [10]:
def mean(a):
    return sum(a) / len(a)

mean_list = np.array(list(map(mean, zip(*array)))).astype('float32')

In [13]:
with open('vector.txt', 'w') as f:
    for item in mean_list.tolist():
        f.write("%s," % item)

In [113]:
comparison = mean_list == array_mean
equal_arrays = comparison.all() 
  
print(equal_arrays) 

True


In [46]:
from numpy import (
    dot, float32 as REAL
)
import numpy as np
from gensim import matutils

mean = matutils.unitvec(np.array(array).mean(axis=0)).astype(REAL)
limited = modeloW2V.wv.vectors_norm
dist = np.dot(limited, mean)

In [15]:
with open('vector.txt', 'w') as f:
    for item in mean.tolist():
        f.write("%s," % item)

In [152]:
best = matutils.argsort(dist, topn=10, reverse=True)
best

array([ 20,  64,  23, 437, 416, 215, 267,  10, 249, 336])

In [71]:
#Mean_list
best = matutils.argsort(dist, topn=10, reverse=True)
best

array([    4,     1,     5,    12,  7443,  6778, 10108,  6038,  9774,
        9615])

# Funcion similar d2v

In [61]:
len(modeloD2V.docvecs.vectors_docs_norm[1])

300

In [140]:
infer = modeloD2V.infer_vector(['conocimiento'])
modeloD2V.docvecs.most_similar([infer], topn=10)

[(215, 0.6421315670013428),
 (267, 0.6080042123794556),
 (10, 0.6039739847183228),
 (271, 0.6016193628311157),
 (416, 0.5938380360603333),
 (437, 0.5845867395401001),
 (295, 0.5813186168670654),
 (375, 0.5812559127807617),
 (39, 0.5790205001831055),
 (19, 0.5768672823905945)]

In [99]:
from numpy import (
    dot, float32 as REAL
)
import numpy as np

from gensim import matutils

mean = [infer*1.0]
array = np.array(mean)
mean = matutils.unitvec(array.mean(axis=0)).astype(REAL)
#array.mean(axis=0)

##### Producto punto y normalizar 
Ordenar de mayor a menor y su cantidad

In [101]:
dist = np.dot(modeloD2V.docvecs.vectors_docs_norm[0:None], mean)
best = matutils.argsort(dist, topn=10 + 2, reverse=True) 
best

array([ 20,  64,  23, 437, 416, 215, 267,  10, 249, 336, 309, 444])

##### Encontrar la palabra

In [ ]:
keyedvectors.index2word[4933]